name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Set up ROS 2 Humble
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
        sudo apt update
        sudo apt install -y ros-humble-desktop
        echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
        source ~/.bashrc

    - name: Install ROS 2 dependencies
      run: |
        source /opt/ros/humble/setup.bash
        sudo apt install -y ros-humble-executive-smach ros-humble-rclpy ros-humble-geometry-msgs ros-humble-std-msgs ros-humble-sensor-msgs

    - name: Install Python dependencies
      run: |
        source /opt/ros/humble/setup.bash
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install pyyaml  # Install pyyaml to handle YAML files
        pip install lark-parser  # Install lark module for parsing
        pip install numpy  # Install numpy for scientific computing
        pip install git+https://github.com/splintered-reality/py_trees.git
        pip install git+https://github.com/splintered-reality/py_trees_ros.git
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source /opt/ros/humble/setup.bash
        source venv/bin/activate
        pytest tests/
