name: Codacy Analysis

on: [pull_request]

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and coverage
      run: |
        pip install codacy-coverage
        coverage run -m pytest
        coverage xml -o coverage.xml

    - name: Upload coverage to Codacy
      run: |
        python-codacy-coverage -r coverage.xml
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
